import React from 'react';
import image1 from '../../e-learning_1.jpg'
import image2 from '../../medical-science-scientific-research-abstract-backdrop-62195483.jpg'
import './Blog.css'

const Blog = () => {
    return (
        <div className='blogs my-5'>
            <div className='single-blog'>
                <div>
                    <img src={image1} alt="" />
                </div>
                <div>
                    <h1 className='w-75 m-auto'>E-learning</h1>
                    <p className='w-75 m-auto'>As part of the coordinated worldwide education response to the COVID-19 pandemic, UNICEF, UNESCO, and the World Bank had surveyed National Education Responses to school closures. The first round of the survey conducted in 118 countries and the second in 149 countries revealed that almost every country included online learning in its education response to the ongoing crisis. 89% of the countries introduced at least one measure to enhance access to online learning devices and connectivity.</p>

                </div>
            </div>



            <div className='single-blog'>
                <div>
                    <img src={image2} alt="" />
                </div>
                <div>
                    <h1 className='w-75 m-auto'>Medicine Nobel goes to scientists who discovered biology of senses</h1>
                    <p className='w-75 m-auto'>Two researchers who discovered the molecular basis for our ability to sense temperature and touch have won this year’s Nobel Prize in Physiology or Medicine. Physiologist David Julius at the University of California in San Francisco (UCSF) used capsaicin — the compound that gives chilli peppers their gustatory kick — to track down a protein called TRPV1 that responds to painful heat. Molecular neurobiologist Ardem Patapoutian at Scripps Research in La Jolla, California, identified receptors in skin and other organs that respond to mechanical forces, such as those generated by touch and pressure.</p>

                </div>
            </div>
        </div>
    );
};

export default Blog;